exclude: ^vendor/|^test/tools/vendor/
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: 83d9cd684c87d95d656c1458ef04895a7f1cbd8e # v8.30.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9 # v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml

  - repo: local
    hooks:
      - id: make-lint
        name: Run make lint
        entry: make lint
        language: system
        pass_filenames: false
        always_run: true
        require_serial: true
